exploration_coef: 1.1
safety_beta: 2.2
safe_reward_floor: -0.4
forget_factor: 0.985
delay_max: 3
reset_window: 50
reset_threshold: 0.2
variance_clip: 4.0
context_scale_q: 10000.0
context_scale_j: 120.0
snr_ref_db: 6.0
