V_list: [20, 23, 27, 31, 36, 41, 47, 54, 61, 70, 79, 89, 100, 113, 127, 143, 161,
 181, 203, 228, 255, 285, 318, 354, 394, 438, 486, 539, 597, 661, 731, 808,
 893, 986]

repeat_each: 3     # 每个V重复次数（>=2可画误差棒）
