seed: 42
out_dir: "semntn/outputs/regret/exp001"

env:
  type: "bernoulli"        # bernoulli | gaussian
  K: 5
  T: 200000
  means: [0.72, 0.70, 0.68, 0.65, 0.60]  # for bernoulli
  # mus: [0.72, 0.70, 0.68, 0.65, 0.60]  # for gaussian
  sigma: 0.1

algo: "sem_ucb"            # ucb1 | eg | sem_ucb

ucb1:
  alpha: 2.0

eg:
  epsilon: 0.05

sem_ucb:
  alpha: 2.0
  lambda0: 0.5
  decay: "log"             # log | invsqrt
  c_decay: 1.0
  predictor: "linear"      # none | linear
  lr: 0.05

plot:
  dpi: 150
  show: false

accept:
  slope_logT_range: [100.0, 1200.0]
  cstar_max: 12.0
