outdir: outputs/regret
save_csv: true

env:
  type: bernoulli
  K: 5
  T: 200000
  means: [0.72, 0.7, 0.68, 0.65, 0.6]
  sigma: 0.1

seeds: [1, 2, 3, 4, 5]
baselines: ["ucb", "eps", "rand", "oracle"]

ucb:
  alpha: 0.5

epsilon: 0.05

plot:
  logx: false
  show_ref_sqrt: true
